services:
  - type: web
    name: chartguesser
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
